DELETE FROM exercise WHERE name IN (
    'Romanian deadlift',
    'Front squat',
    'Tempo squat',
    'Hip thrust',
    'Leg curl',
    'Single leg curl',
    'Leg extensions',
    'Paused deadlift',
    'Deficit deadlift',
    'Paused squat',
    'Pin squat',
    'Paused bench',
    'Dumbell bench',
    'Spoto press',
    'Pin press',
    'Larsen press',
    'Close-grip bench press',
    'Tricep extensions',
    'Dumbell skullcrushers',
    'Incline curls',
    'Cable curls',
    'EZ bar curls',
    'Face-away cable curls',
    'Lat pulldown',
    'T-Bar row',
    'Dumbell shoulder press',
    'Lateral raise',
    'Face pull',
    'Rear delt flies',
    'Cable chest flies',
    'Machine chest flies',
    'Leg raises');
