CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    userName VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (userName, password) VALUES ('test', 'password')